language: python
python:
  - 2.7
  - 3.6
  - pypy
  - pypy3
  - nightly
env:
  - TOXENV=pytest29
  - TOXENV=pytest30
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=flake8
install:
  - pip install tox-travis
script:
  - tox
